version: '2.4'

volumes:
  cache: &tmpfsConfig
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  composer: *tmpfsConfig
  logs: *tmpfsConfig
  vendor: *tmpfsConfig

services:
  php:
    build:
      context: .
      target: base
    user: "33"
    volumes:
      - .:/app:ro
      - cache:/app/var/cache
      - composer:/composer
      - logs:/app/var/log
      - vendor:/app/vendor

  nginx:
    image: nginx
    volumes:
      - ./opt/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      php:
        condition: service_started
