version: '2.4'

services:
  php:
    build:
      context: .
      target: base
    user: "33"
    volumes:
      - .:/app
    tmpfs:
      - /app/vendor:uid=33
      - /composer:uid=33

  nginx:
    image: nginx
    volumes:
      - ./opt/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      php:
        condition: service_started
